#!/bin/bash

# Git commit hook that checks that there are no source files that contain
# trailing whitespace or too long lines. (rst files may contain too long lines,
# Python files may not.)

tmp=`tempfile`
pythonfiles=`git-ls-files | grep py`
error_file=`tempfile`

function check_trailing_whitespace
{
    grep -n " $" *.py doc/*.{rst,py,hrst} > "$tmp"
    if [ "`cat $tmp`" != "" ]
    then
        echo
        echo "There is a trailing whitespace:"
        echo
        cat "$tmp"
    fi
}

function check_long_lines
{
    grep -n ".\{82\}" $pythonfiles | grep -v 'http://' > "$tmp"
    if [ "`cat $tmp`" != "" ]
    then
        echo
        echo "There is Python code that is longer than 80 lines:"
        echo
        cat "$tmp"
    fi
}

check_trailing_whitespace >> "$error_file"
check_long_lines >> "$error_file"

if [ "$(cat $error_file)" != "" ]
then
    echo "pre-commit: No commit made."
    cat $error_file
    exit 1
fi

rm "$tmp"
rm "$error_file"
