#!/bin/sh

if [ "$#" = 0 -o "$1" = "-h" -o "$1" = "--help" ];
then
    cat <<END
pushdoc <username>

Description:
    Copies the documentation of Heapkeeper to heapkeeper.org.

Usage:
    Run pushdoc without arguments and type the heapkeeper.org password.

Prerequitites:
    This script needs the ncftp program (which contains the ncftpput command).
    In Ubuntu, just install the ncftp package.

Note:
    You can run the script from any directory, it will work. (Unless you copy
    the script itself to somewhere else, in which case it will not.)
END
exit
fi

dir=`dirname "$0"`
echo "heapkeeper.org password:"
ncftpput -R -u "$1" ftp.heapkeeper.org htdocs "$dir"/../doc/_build/html/*
